# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fastapi-testnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rgcrgerges.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9704d254de6e43efb410513aeff0e82e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7c81f7dcc0dc4cc98f65b668e514c51b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rgcrgerges.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9704d254de6e43efb410513aeff0e82e }}/fastapi2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-testnew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7ac220c5ffbe4eeb9a94038f89a9062c }}
        images: 'rgcrgerges.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9704d254de6e43efb410513aeff0e82e }}/fastapi2:${{ github.sha }}'